export default defineAppConfig({
  ui: {
    icons: {
      // Keep all UI icon keys on the local solar collection to avoid lucide fallback warnings.
      arrowDown: 'solar:alt-arrow-down-bold-duotone',
      arrowLeft: 'solar:alt-arrow-left-bold-duotone',
      arrowRight: 'solar:alt-arrow-right-bold-duotone',
      arrowUp: 'solar:alt-arrow-up-bold-duotone',
      caution: 'solar:danger-triangle-bold-duotone',
      copy: 'solar:copy-bold-duotone',
      copyCheck: 'solar:check-square-bold-duotone',
      dark: 'solar:moon-bold-duotone',
      eye: 'solar:eye-bold-duotone',
      eyeOff: 'solar:eye-closed-bold-duotone',
      file: 'solar:file-bold-duotone',
      folder: 'solar:folder-bold-duotone',
      folderOpen: 'solar:folder-open-bold-duotone',
      hash: 'solar:hashtag-bold-duotone',
      light: 'solar:sun-2-bold-duotone',
      menu: 'solar:hamburger-menu-bold-duotone',
      minus: 'solar:minus-circle-bold-duotone',
      panelClose: 'solar:square-arrow-left-bold-duotone',
      panelOpen: 'solar:square-arrow-right-bold-duotone',
      plus: 'solar:add-circle-bold-duotone',
      reload: 'solar:refresh-bold-duotone',
      search: 'solar:magnifer-bold-duotone',
      stop: 'solar:stop-circle-bold-duotone',
      system: 'solar:monitor-bold-duotone',
      tip: 'solar:lightbulb-bold-duotone',
      upload: 'solar:upload-bold-duotone',
      loading: 'solar:refresh-bold-duotone',
      close: 'solar:close-circle-bold-duotone',
      check: 'solar:check-circle-bold-duotone',
      info: 'solar:info-circle-bold-duotone',
      warning: 'solar:danger-triangle-bold-duotone',
      error: 'solar:danger-circle-bold-duotone',
      success: 'solar:verified-check-bold-duotone',
      external: 'solar:alt-arrow-right-bold-duotone',
      chevronDown: 'solar:alt-arrow-down-bold-duotone',
      chevronRight: 'solar:alt-arrow-right-bold-duotone',
      chevronLeft: 'solar:alt-arrow-left-bold-duotone',
      ellipsis: 'solar:menu-dots-bold-duotone',
    },
  },
})
